* Bibliography

** Brussels
- Janssens (2012) provides an in-depth overview and analysis of the measures 
  applied by the Flemish Government in order to control the LL and regulate 
  language use in the public space of the Brussels periphery

- Janssens (2013 in dutch) provides a survey-like booklet with statistics?

- Ben-Rafael and Ben-Rafael (2012 in french) insightfully examine the LL of several 
  places in Brussels as part of a larger study of the seemingly chaotic LL of Belgium.

- 'the spatial turn' in social sciences (Benwell and Stokoe 2006; Vigouroux 2009; Pennycook 2010)

- Moreover, Collins and Slembrouck (2007) examine the landscape of polyglot migrant 
  neighbourhoods in Ghent (Belgium) and suggest that one publicly displayed sign can 
  be addressed from different pedestrian participant perspectives.

- Survey by Willaert [[http://www.bisa.irisnet.be/bestanden/publicaties/statistische-dossiers/SD42_buurtatlas_van_de_bevolking_van_het_brussels_hoofdstedelijk_gewest_bij_de_aanvang_van_de_21ste_eeuw.pdf][link]]

*** Vandenbroucke 2014

- Title: Language visibility, functionality and meaning across various TimeSpace scales in Brussels' multilingual landscapes.
- Multiscalarisation on three levels (Baeten 2001):
  + historical evolution since the fourteenth century from a relatively small monolingual, 
    Flemish city into a national bilingual and bicultural capital
  + Belgianisation, NATO-isation and Europeanisation
  + globalised diasporas and intensified transnational mobilities have also resulted 
    in the rapid "transnationalisation" of Brussels' population from both 'below' 
    (ethnic immigrant minorities) and 'above' (transnational elites of expats, professionals and tourists).
- Question: which languages are visible (in terms of frequency and salience) and have communicative value 
which is based on such LL visibility in the different metropolitan areas?

- Places:
  * Grand place
  * Rue Antoine Dansaert (flemish-assertive neighbourhood).
  * Chaussee d'Ixelles (frech-oriented in the south). 

- Language visibility score:
  + Monolingual unit, unit recieves 4
  + Equivalent multilingual (information equally presented in X and Y), each unit recieves 2
  + Unevenly distributed, dominant unit recieves 3, other unit 1
For each unit, compute the proportion it represents from the entire unit set. (Term freq.)

* Findings/Hypothesis
** Brussels
- VUB and Quartier Nord is more dutch-oriented
- Along the rails arriving/leaving Brussels.

* Ideas
** Spot significant places
A sort of data-driven exploration of the linguistic landscape(?). Check which areas seem to behave 
differently from a particular "null hypothesis" (languages are evenly distributed).

** Significance testing, but how?
It would be nice to have a method to compute a p-value for a given tile. Perhaps one could filtered out 
blocks where the total number of tweets lies below a threshold. 
This threshold should be also statistically grounded and interpreted against /statistical power/.

** Make clear the assumption that this work relies on
*** Twitter-bias 
- Paper about (Language use(rs) in Twitter)
- A reasonable dissonance of the project is that proportions of languages in Twitter would be biased
since the use of Twitter is not independant of the language of the potential Twitter-user. 
Although this is true (and interesting in itself for research), the question raises then
about what is it that Twitter is a bias of when considering language use. Let say that one
could better estimate language use via nationality or even 
   + /native language/ as given in the city census. This will exclude people from other cities and places, and be also biased.
   + /saliency/ as per Vandenbroucke 2014. But "the linguistic landscape in itself does not necessarily 
   reflect the ethnolinguistic diversity of all inhabiting majority and minority communities" and 
   "Relative street visibility does indeed go together with demographic detail to a certain degree, 
   but it does not coincide with it".
In the absence of other data, we can still claim that, in despite of a unresearched bias, Twitter data can
still be used for mapping languages and language use to city areas.
- We do not really expect to find bias in the way french-speakers and dutch-speakers use Twitter?

*** Others
- For sparseness reasons, focus is on the Tweet-level (instead of user level). This implies that
the model is not protected against overproductive Twitters. (which could be eliminated from the dabase
in a pre-filtering phase).
- Clustering is arguably excluded in the first place, because most modern cities in Europe do not show such
a degree of gettoization.

** Further research
- Network analysis of Twitter-users which can be located to a given city. There are already 
language-based network studies on a national and international level (TODO). Still these studies
are still far away from the level of granularity which fits real language use. A good framework
to study this is the city (- check this with Hunning). Can we locate language-based networks
of Twitter-users to certain areas in cities?

** TODO Non-significant bzw. random results could be due to a variety of reasons
